/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3ef",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#2c1600",
        "primary-container": "#8b9d83",
        "inverse-primary": "#b9ccb0",
        primary: "#52634c",
        "surface-tint": "#52634c",
        "surface-container": "#efeeea",
        "on-secondary-container": "#7a532a",
        "tertiary-fixed": "#d1e4fb",
        surface: "#fbf9f5",
        "secondary-fixed-dim": "#f0bd8b",
        "on-primary-fixed": "#101f0d",
        tertiary: "#4e6073",
        "on-surface": "#1b1c1a",
        "primary-fixed": "#d5e8cb",
        "secondary-container": "#ffca98",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "tertiary-container": "#879aaf",
        "surface-dim": "#dbdad6",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2de",
        "on-surface-variant": "#444841",
        "on-tertiary-container": "#203243",
        "tertiary-fixed-dim": "#b5c8df",
        "on-background": "#1b1c1a",
        "on-primary-fixed-variant": "#3b4b36",
        "on-secondary-fixed-variant": "#623f18",
        secondary: "#7d562d",
        background: "#fbf9f5",
        "outline-variant": "#c4c8be",
        "on-tertiary-fixed": "#091d2e",
        "primary-fixed-dim": "#b9ccb0",
        "secondary-fixed": "#ffdcbd",
        "on-primary-container": "#253420",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f0ed",
        "surface-container-high": "#eae8e4",
        outline: "#747870",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e4e2de",
        "surface-bright": "#fbf9f5",
        "on-tertiary-fixed-variant": "#36485b",
        "error-container": "#ffdad6",
        "inverse-surface": "#30312e",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-xl": "48px",
        gutter: "16px",
        "stack-md": "16px",
        "margin-page": "24px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "label-md": ["Inter_500Medium"],
        "headline-md": ["EBGaramond_500Medium"],
        "body-md": ["Inter_400Regular"],
        "headline-lg-mobile": ["EBGaramond_500Medium"],
        "body-lg": ["Inter_400Regular"],
        caption: ["Inter_400Regular"],
        "title-lg": ["EBGaramond_600SemiBold"],
        "headline-lg": ["EBGaramond_500Medium"],
        display: ["EBGaramond_500Medium"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em" }],
        "headline-md": ["24px", { lineHeight: "32px" }],
        "body-md": ["16px", { lineHeight: "26px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "0.01em" }],
        caption: ["12px", { lineHeight: "16px" }],
        "title-lg": ["20px", { lineHeight: "28px" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.01em" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em" }],
      },
    },
  },
  plugins: [],
};
